[package]
name = "papillae"
version = "0.1.9"
edition = "2021"
authors = ["Nick Stone <nicholasestone@proton.me>"]

[dependencies]
futures = "0.3.30"
iced = { version = "0.12.1", features = ["image", "advanced"] }
ralston = { version = "0.2.1", git = "https://github.com/nstone8/ralston" }
